

extern INT16U	g_uwROPVolt;
extern INT16U	g_uwSOPVolt;
extern INT16U	g_uwTOPVolt;
extern INT16U	g_uwROPCurr;
extern INT16U	g_uwSOPCurr;
extern INT16U	g_uwTOPCurr;
extern INT32S	g_dwOPWatt;
extern INT32S	g_dwOPVA;
extern INT32S	g_dwROPWatt;
extern INT32S	g_dwROPVA;
extern INT32S	g_dwSOPWatt;
extern INT32S	g_dwSOPVA;
extern INT32S	g_dwTOPWatt;
extern INT32S	g_dwTOPVA;
extern INT16S	g_wOPPercent;
extern INT16S	g_wROPPercent;
extern INT16S	g_wSOPPercent;
extern INT16S	g_wTOPPercent;
extern INT16U	g_uwOPFreq;
extern INT32S	g_dwOPMaxPower;
extern INT16S	g_wOverLoadBypass;
extern INT32S	g_dwOPWattFilter;
extern INT32S	g_dwSmartOPWatt;
extern INT32S	g_dwSmartOPVA;
extern INT16U	g_uwRSmartOPVolt;
extern INT16U	g_uwRSmartOPCurr;
extern INT16U   g_uwSmartOPFreq;
extern INT32S	g_dwSmartOPWattFilter;

extern void sROPVoltAdj(INT16U uROPVolt);
extern void sSOPVoltAdj(INT16U uSOPVolt);
extern void sTOPVoltAdj(INT16U uTOPVolt);
extern void sROPCurrAdj(INT16U uROPCurr);
extern void sSOPCurrAdj(INT16U uSOPCurr);
extern void sTOPCurrAdj(INT16U uTOPCurr);
extern void sROPShareCurrAdj(INT16U uROPShareCurr);
extern void sSOPShareCurrAdj(INT16U uSOPShareCurr);
extern void sTOPShareCurrAdj(INT16U uTOPShareCurr);
extern void	sOPFreqCal(INT16U uwOPPeriod);
extern void sOPZeroLossClr(void);
extern void	sOPZeroLossChk(INT16U uwFilter);	
extern void	sOPWattAdj(INT32S dwROPWatt, INT32S dwSOPWatt, INT32S dwTOPWatt);
extern void	sOPRTWattAdj(INT32S dwROPWatt, INT32S dwSOPWatt, INT32S dwTOPWatt);
extern void	sOPVAAdj(void);
extern void sSmartOPWattAdj(INT32S dwRSmartOPWatt, INT32S dwSSmartOPWatt, INT32S dwTSmartOPWatt);
extern void sSmartOPVAAdj(void);
extern void sSmartOPFreqCal(void);
extern void sOPPercentCal(void);
extern void sOverLoadChk(void);
extern void sInvOPShortChk(INT16U uwFilter);
extern void sParaShareCurChk(void);
extern void sParaSShareCurChk(void);
extern void sParaTShareCurChk(void);
extern void sOPVoltTransferRatioCal(void);
extern void	sGridCurrCal(void);
extern void sRSmartOPCurrAdj(INT16U uRSmartOPCurr);
extern void sRSmartOPVoltAdj(INT16U uRSmartOPVolt);


