# FIXED

KERNEL/SOURCE/OS_CORE.obj: ../KERNEL/SOURCE/OS_CORE.c
KERNEL/SOURCE/OS_CORE.obj: Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/Kernel/Kernel.h
KERNEL/SOURCE/OS_CORE.obj: Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/OS_CPU.h
KERNEL/SOURCE/OS_CORE.obj: Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/os_config.h

../KERNEL/SOURCE/OS_CORE.c: 
Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/Kernel/Kernel.h: 
Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/OS_CPU.h: 
Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/os_config.h: 
