# FIXED

KERNEL/SOURCE/OS_EVENT.obj: ../KERNEL/SOURCE/OS_EVENT.C
KERNEL/SOURCE/OS_EVENT.obj: Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/Kernel/Kernel.h
KERNEL/SOURCE/OS_EVENT.obj: Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/OS_CPU.h
KERNEL/SOURCE/OS_EVENT.obj: Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/os_config.h

../KERNEL/SOURCE/OS_EVENT.C: 
Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/Kernel/Kernel.h: 
Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/OS_CPU.h: 
Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/os_config.h: 
