# FIXED

KERNEL/SOURCE/OS_TIMER.obj: ../KERNEL/SOURCE/OS_TIMER.c
KERNEL/SOURCE/OS_TIMER.obj: Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/Kernel/Kernel.h
KERNEL/SOURCE/OS_TIMER.obj: Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/OS_CPU.h
KERNEL/SOURCE/OS_TIMER.obj: Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/os_config.h
KERNEL/SOURCE/OS_TIMER.obj: Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/Kernel/source/OS_HEAD.h
KERNEL/SOURCE/OS_TIMER.obj: Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/OS_CPU.h

../KERNEL/SOURCE/OS_TIMER.c: 
Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/Kernel/Kernel.h: 
Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/OS_CPU.h: 
Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/os_config.h: 
Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/Kernel/source/OS_HEAD.h: 
Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/OS_CPU.h: 
