# FIXED

KERNEL/SOURCE/OS_EVENT.obj: ../KERNEL/SOURCE/OS_EVENT.C
KERNEL/SOURCE/OS_EVENT.obj: Z:/VMVare\ Map\ File/IVPM10K/FLS-GPINV-IVPA10K1011/Kernel/Kernel.h
KERNEL/SOURCE/OS_EVENT.obj: Z:/VMVare\ Map\ File/IVPM10K/FLS-GPINV-IVPA10K1011/kernel/ports/OS_CPU.h
KERNEL/SOURCE/OS_EVENT.obj: Z:/VMVare\ Map\ File/IVPM10K/FLS-GPINV-IVPA10K1011/kernel/ports/os_config.h

../KERNEL/SOURCE/OS_EVENT.C: 
Z:/VMVare\ Map\ File/IVPM10K/FLS-GPINV-IVPA10K1011/Kernel/Kernel.h: 
Z:/VMVare\ Map\ File/IVPM10K/FLS-GPINV-IVPA10K1011/kernel/ports/OS_CPU.h: 
Z:/VMVare\ Map\ File/IVPM10K/FLS-GPINV-IVPA10K1011/kernel/ports/os_config.h: 
