# FIXED

KERNEL/SOURCE/OS_SHELL.obj: ../KERNEL/SOURCE/OS_SHELL.c
KERNEL/SOURCE/OS_SHELL.obj: Z:/VMVare\ Map\ File/IVPM10K/FLS-GPINV-IVPA10K1011/Kernel/kernel.h
KERNEL/SOURCE/OS_SHELL.obj: Z:/VMVare\ Map\ File/IVPM10K/FLS-GPINV-IVPA10K1011/kernel/ports/OS_CPU.h
KERNEL/SOURCE/OS_SHELL.obj: Z:/VMVare\ Map\ File/IVPM10K/FLS-GPINV-IVPA10K1011/kernel/ports/os_config.h

../KERNEL/SOURCE/OS_SHELL.c: 
Z:/VMVare\ Map\ File/IVPM10K/FLS-GPINV-IVPA10K1011/Kernel/kernel.h: 
Z:/VMVare\ Map\ File/IVPM10K/FLS-GPINV-IVPA10K1011/kernel/ports/OS_CPU.h: 
Z:/VMVare\ Map\ File/IVPM10K/FLS-GPINV-IVPA10K1011/kernel/ports/os_config.h: 
