# FIXED

KERNEL/SOURCE/OS_SHELL.obj: ../KERNEL/SOURCE/OS_SHELL.c
KERNEL/SOURCE/OS_SHELL.obj: Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/Kernel/kernel.h
KERNEL/SOURCE/OS_SHELL.obj: Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/OS_CPU.h
KERNEL/SOURCE/OS_SHELL.obj: Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/os_config.h

../KERNEL/SOURCE/OS_SHELL.c: 
Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/Kernel/kernel.h: 
Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/OS_CPU.h: 
Z:/VMVare\ Map\ File/IVQM3524/FLS-GPINV-IVQMSIGM/kernel/ports/os_config.h: 
