################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SHELL = cmd.exe

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../App_source/Adc.c \
../App_source/AdcATE.c \
../App_source/AnoAssistant.c \
../App_source/Bat.c \
../App_source/Bus.c \
../App_source/CanInModDeal.c \
../App_source/Candriver.c \
../App_source/Commfunc.c \
../App_source/Configtable.c \
../App_source/DcDc.c \
../App_source/Ecap.c \
../App_source/Eeprom.c \
../App_source/Example_Flash2833x_API.c \
../App_source/Fan.c \
../App_source/Fault.c \
../App_source/Gen.c \
../App_source/Grid.c \
../App_source/GridStandard.c \
../App_source/I2cApp.c \
../App_source/I2cDrv.c \
../App_source/Inv.c \
../App_source/Inverter.c \
../App_source/Ipoms.c \
../App_source/Isocheck.c \
../App_source/Llc.c \
../App_source/Logic.c \
../App_source/Main.c \
../App_source/Monitor.c \
../App_source/MonitorModbus.c \
../App_source/MonitorProtocol.c \
../App_source/MonitorSci.c \
../App_source/Mppt.c \
../App_source/Pll.c \
../App_source/Powerderating.c \
../App_source/PvInvComm.c \
../App_source/Relay.c \
../App_source/Spia.c \
../App_source/Systable.c \
../App_source/System.c \
../App_source/Task.c \
../App_source/Upgrade.c \
../App_source/Versioncontrol.c 

C_DEPS += \
./App_source/Adc.d \
./App_source/AdcATE.d \
./App_source/AnoAssistant.d \
./App_source/Bat.d \
./App_source/Bus.d \
./App_source/CanInModDeal.d \
./App_source/Candriver.d \
./App_source/Commfunc.d \
./App_source/Configtable.d \
./App_source/DcDc.d \
./App_source/Ecap.d \
./App_source/Eeprom.d \
./App_source/Example_Flash2833x_API.d \
./App_source/Fan.d \
./App_source/Fault.d \
./App_source/Gen.d \
./App_source/Grid.d \
./App_source/GridStandard.d \
./App_source/I2cApp.d \
./App_source/I2cDrv.d \
./App_source/Inv.d \
./App_source/Inverter.d \
./App_source/Ipoms.d \
./App_source/Isocheck.d \
./App_source/Llc.d \
./App_source/Logic.d \
./App_source/Main.d \
./App_source/Monitor.d \
./App_source/MonitorModbus.d \
./App_source/MonitorProtocol.d \
./App_source/MonitorSci.d \
./App_source/Mppt.d \
./App_source/Pll.d \
./App_source/Powerderating.d \
./App_source/PvInvComm.d \
./App_source/Relay.d \
./App_source/Spia.d \
./App_source/Systable.d \
./App_source/System.d \
./App_source/Task.d \
./App_source/Upgrade.d \
./App_source/Versioncontrol.d 

OBJS += \
./App_source/Adc.obj \
./App_source/AdcATE.obj \
./App_source/AnoAssistant.obj \
./App_source/Bat.obj \
./App_source/Bus.obj \
./App_source/CanInModDeal.obj \
./App_source/Candriver.obj \
./App_source/Commfunc.obj \
./App_source/Configtable.obj \
./App_source/DcDc.obj \
./App_source/Ecap.obj \
./App_source/Eeprom.obj \
./App_source/Example_Flash2833x_API.obj \
./App_source/Fan.obj \
./App_source/Fault.obj \
./App_source/Gen.obj \
./App_source/Grid.obj \
./App_source/GridStandard.obj \
./App_source/I2cApp.obj \
./App_source/I2cDrv.obj \
./App_source/Inv.obj \
./App_source/Inverter.obj \
./App_source/Ipoms.obj \
./App_source/Isocheck.obj \
./App_source/Llc.obj \
./App_source/Logic.obj \
./App_source/Main.obj \
./App_source/Monitor.obj \
./App_source/MonitorModbus.obj \
./App_source/MonitorProtocol.obj \
./App_source/MonitorSci.obj \
./App_source/Mppt.obj \
./App_source/Pll.obj \
./App_source/Powerderating.obj \
./App_source/PvInvComm.obj \
./App_source/Relay.obj \
./App_source/Spia.obj \
./App_source/Systable.obj \
./App_source/System.obj \
./App_source/Task.obj \
./App_source/Upgrade.obj \
./App_source/Versioncontrol.obj 

OBJS__QUOTED += \
"App_source\Adc.obj" \
"App_source\AdcATE.obj" \
"App_source\AnoAssistant.obj" \
"App_source\Bat.obj" \
"App_source\Bus.obj" \
"App_source\CanInModDeal.obj" \
"App_source\Candriver.obj" \
"App_source\Commfunc.obj" \
"App_source\Configtable.obj" \
"App_source\DcDc.obj" \
"App_source\Ecap.obj" \
"App_source\Eeprom.obj" \
"App_source\Example_Flash2833x_API.obj" \
"App_source\Fan.obj" \
"App_source\Fault.obj" \
"App_source\Gen.obj" \
"App_source\Grid.obj" \
"App_source\GridStandard.obj" \
"App_source\I2cApp.obj" \
"App_source\I2cDrv.obj" \
"App_source\Inv.obj" \
"App_source\Inverter.obj" \
"App_source\Ipoms.obj" \
"App_source\Isocheck.obj" \
"App_source\Llc.obj" \
"App_source\Logic.obj" \
"App_source\Main.obj" \
"App_source\Monitor.obj" \
"App_source\MonitorModbus.obj" \
"App_source\MonitorProtocol.obj" \
"App_source\MonitorSci.obj" \
"App_source\Mppt.obj" \
"App_source\Pll.obj" \
"App_source\Powerderating.obj" \
"App_source\PvInvComm.obj" \
"App_source\Relay.obj" \
"App_source\Spia.obj" \
"App_source\Systable.obj" \
"App_source\System.obj" \
"App_source\Task.obj" \
"App_source\Upgrade.obj" \
"App_source\Versioncontrol.obj" 

C_DEPS__QUOTED += \
"App_source\Adc.d" \
"App_source\AdcATE.d" \
"App_source\AnoAssistant.d" \
"App_source\Bat.d" \
"App_source\Bus.d" \
"App_source\CanInModDeal.d" \
"App_source\Candriver.d" \
"App_source\Commfunc.d" \
"App_source\Configtable.d" \
"App_source\DcDc.d" \
"App_source\Ecap.d" \
"App_source\Eeprom.d" \
"App_source\Example_Flash2833x_API.d" \
"App_source\Fan.d" \
"App_source\Fault.d" \
"App_source\Gen.d" \
"App_source\Grid.d" \
"App_source\GridStandard.d" \
"App_source\I2cApp.d" \
"App_source\I2cDrv.d" \
"App_source\Inv.d" \
"App_source\Inverter.d" \
"App_source\Ipoms.d" \
"App_source\Isocheck.d" \
"App_source\Llc.d" \
"App_source\Logic.d" \
"App_source\Main.d" \
"App_source\Monitor.d" \
"App_source\MonitorModbus.d" \
"App_source\MonitorProtocol.d" \
"App_source\MonitorSci.d" \
"App_source\Mppt.d" \
"App_source\Pll.d" \
"App_source\Powerderating.d" \
"App_source\PvInvComm.d" \
"App_source\Relay.d" \
"App_source\Spia.d" \
"App_source\Systable.d" \
"App_source\System.d" \
"App_source\Task.d" \
"App_source\Upgrade.d" \
"App_source\Versioncontrol.d" 

C_SRCS__QUOTED += \
"../App_source/Adc.c" \
"../App_source/AdcATE.c" \
"../App_source/AnoAssistant.c" \
"../App_source/Bat.c" \
"../App_source/Bus.c" \
"../App_source/CanInModDeal.c" \
"../App_source/Candriver.c" \
"../App_source/Commfunc.c" \
"../App_source/Configtable.c" \
"../App_source/DcDc.c" \
"../App_source/Ecap.c" \
"../App_source/Eeprom.c" \
"../App_source/Example_Flash2833x_API.c" \
"../App_source/Fan.c" \
"../App_source/Fault.c" \
"../App_source/Gen.c" \
"../App_source/Grid.c" \
"../App_source/GridStandard.c" \
"../App_source/I2cApp.c" \
"../App_source/I2cDrv.c" \
"../App_source/Inv.c" \
"../App_source/Inverter.c" \
"../App_source/Ipoms.c" \
"../App_source/Isocheck.c" \
"../App_source/Llc.c" \
"../App_source/Logic.c" \
"../App_source/Main.c" \
"../App_source/Monitor.c" \
"../App_source/MonitorModbus.c" \
"../App_source/MonitorProtocol.c" \
"../App_source/MonitorSci.c" \
"../App_source/Mppt.c" \
"../App_source/Pll.c" \
"../App_source/Powerderating.c" \
"../App_source/PvInvComm.c" \
"../App_source/Relay.c" \
"../App_source/Spia.c" \
"../App_source/Systable.c" \
"../App_source/System.c" \
"../App_source/Task.c" \
"../App_source/Upgrade.c" \
"../App_source/Versioncontrol.c" 


